var rarities = [{
  "item":"clothmask-leopard",
  "name": "Cloth Mask (Leopard)",
  "clothetype": "face",
  "crate": "desperado",
  "cratename": "Desperado Crate",
  "rarity": "Red",
  "raritytext": "Legendary",
  "probability": "0.16",
  "bp": "1920"},
{
  "item":"leatherhoodie-black",
  "name": "Leather Hoodie (Black)",
  "clothetype": "outer",
  "crate": "desperado",
  "cratename": "Desperado Crate",
  "rarity": "Pink",
  "raritytext": "Epic",
  "probability": "0.32",
  "bp": "960"},
{
  "item":"longsleevedleather-black",
  "name": "Long Sleeved Leather Shirt",
  "clothetype": "torso",
  "crate": "desperado",
  "cratename": "Desperado Crate",
  "rarity": "Purple",
  "raritytext": "Elite",
  "probability": "0.6",
  "bp": "480"},
{
  "item":"hornrimmedglasses-black",
  "name": "Horn-rimmed Glasses (Black)",
  "clothetype": "eyes",
  "crate": "desperado",
  "cratename": "Desperado Crate",
  "rarity": "Blue",
  "raritytext": "Rare",
  "probability": "4.5",
  "bp": "240"},
  {
    "item":"baggypants-brown",
    "name": "Baggy Pants (Brown)",
    "clothetype": "legs",
    "crate": "desperado",
    "cratename": "Desperado Crate",
    "rarity": "Green",
    "raritytext": "Special",
    "probability": "5",
    "bp": "120"},
{
  "item":"militarytrousers-black",
  "name": "Military Trousers (Black)",
  "clothetype": "legs",
  "crate": "militia",
  "cratename": "Militia Crate",
  "rarity": "Light Gray",
  "raritytext": "Classic",
  "probability": "6.5",
  "bp": "60"},
{
  "item":"vintagepoloshirt",
  "name": "Vintage Polo Shirt",
  "clothetype": "torso",
  "crate": "militia",
  "cratename": "Militia Crate",
  "rarity": "Dark Gray",
  "raritytext": "Common",
  "probability": "20",
  "bp": "30"}
]